[theme]
primaryColor = "#1E88E5"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2D2D2D"
textColor = "#FFFFFF"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
serverAddress = "localhost"
serverPort = 8501 